// <auto-generated />
using System;
using GimnasioGrupo2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GimnasioGrupo2.Migrations
{
    [DbContext(typeof(GimnasioContext))]
    [Migration("20251127220227_AddObjetoPerdido_Entregado")]
    partial class AddObjetoPerdido_Entregado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GimnasioGrupo2.Models.Cliente", b =>
                {
                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GimnasioId")
                        .HasColumnType("int");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<bool>("MembresiaVigente")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Dni");

                    b.HasIndex("GimnasioId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.ClienteMembresia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteDni")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoMembresiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteDni");

                    b.HasIndex("TipoMembresiaId");

                    b.ToTable("ClienteMembresias");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.Gimnasio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Gimnasios");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.ObjetoPerdido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteDni")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Entregado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEncontrado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntregado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteDni");

                    b.ToTable("ObjetosPerdidos");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDeEjercicios")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteDni")
                        .HasColumnType("int");

                    b.Property<int?>("GimnasioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("TiempoEstimado")
                        .HasColumnType("float");

                    b.Property<int>("TipoRutinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteDni");

                    b.HasIndex("GimnasioId");

                    b.HasIndex("TipoRutinaId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.TipoMembresia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposMembresia");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.TipoRutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposRutina");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.Cliente", b =>
                {
                    b.HasOne("GimnasioGrupo2.Models.Gimnasio", null)
                        .WithMany("Clientes")
                        .HasForeignKey("GimnasioId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.ClienteMembresia", b =>
                {
                    b.HasOne("GimnasioGrupo2.Models.Cliente", "Cliente")
                        .WithMany("ClienteMembresias")
                        .HasForeignKey("ClienteDni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GimnasioGrupo2.Models.TipoMembresia", "TipoMembresia")
                        .WithMany("ClienteMembresias")
                        .HasForeignKey("TipoMembresiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoMembresia");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.ObjetoPerdido", b =>
                {
                    b.HasOne("GimnasioGrupo2.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteDni")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.Rutina", b =>
                {
                    b.HasOne("GimnasioGrupo2.Models.Cliente", "Cliente")
                        .WithMany("Rutinas")
                        .HasForeignKey("ClienteDni")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GimnasioGrupo2.Models.Gimnasio", null)
                        .WithMany("Rutinas")
                        .HasForeignKey("GimnasioId");

                    b.HasOne("GimnasioGrupo2.Models.TipoRutina", "TipoRutina")
                        .WithMany("Rutinas")
                        .HasForeignKey("TipoRutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoRutina");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.Cliente", b =>
                {
                    b.Navigation("ClienteMembresias");

                    b.Navigation("Rutinas");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.Gimnasio", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Rutinas");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.TipoMembresia", b =>
                {
                    b.Navigation("ClienteMembresias");
                });

            modelBuilder.Entity("GimnasioGrupo2.Models.TipoRutina", b =>
                {
                    b.Navigation("Rutinas");
                });
#pragma warning restore 612, 618
        }
    }
}
